WMass/WRemnants

- notebooks/PlotScratch.ipynb
- wremnants/boostHistHelpers.py
- wremnants/histselections.py
Also adding scripts to select regions and make operations on boost hists, useful for plotting and combine
> Add a kind of sloppy plotting notebook example

- README.md
For the rookie user, to avoid messing around the very first time
(Also my first pull request here ...)
> Update readme with instructions

- scripts/histmakers/mw_with_mu_eta_pt.py
- wremnants/CardTool.py
- wremnants/datasets/datagroups.py
- wremnants/include/theory_corrections.h
- wremnants/theory_tools.py
A few other trivial things are also included (note for example that the default argument for the helper function doesn't work, so it might as well not be set)
> Fix bug from setting negative helicity contributions to zero

- scripts/histmakers/mw_with_mu_eta_pt.py
> removing dummy quit() !

- wremnants/boostHistHelpers.py
- wremnants/datasets/datagroups.py
- wremnants/plot_tools.py
- wremnants/syst_tools.py
option to combine histograms for wplus and wminus for plotting
> option to combine wp and wm hists for plotting + comments

- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/histmakers/w_z_gen_dists.py
- scripts/plotting/makeDataMCStackPlot.py
- wremnants/datasets/datasetDict_v9.py
- wremnants/datasets/datasets2016.py
- update the histomaker script for W-selection
- minor updates to plotting script
***Validation
- runs on CERN machine
- tests running on Pisa machine.
> Update the histmaker scripts for w-selection

- scripts/combine/setupCombineWMass.py
- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
- utilities/boostHistHelpers.py
- utilities/common.py
- wremnants/CardTool.py
- wremnants/combine_helpers.py
- wremnants/datasets/datagroups.py
- wremnants/syst_tools.py
- wremnants/theory_tools.py
* Separate function for reusability
* Ability to add SCETlib, either as the -1 component in helicity splitting, or only for low pT in pT split
* Support for excluding bins with the .j syntax
> Restructure scale uncertainty for combine

- wremnants/datasets/datasetsLowPU.py
As in the title. Left the old samples commented for potential debugging later.
> New lowPU signal samples with MiNNLO fix

- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
- utilities/common.py
- utilities/output_tools.py
- wremnants/datasets/datasets2016.py
- wremnants/muon_calibration.py
> Fix path at MIT

- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
- wremnants/include/muon_validation.h
- wremnants/muon_calibration.py
- wremnants/muon_validation.py
cvhbs branches were plotted in the validation histograms. Changing them to cvh for our updated nanoaod files
> changing cvhbs stuff to cvh

- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
Remove aux hists from recoil in wlike
> Remove aux hists from recoil in wlike

- .github/workflows/main.yml
- scripts/analysisTools/plotUtils/utility.py
- scripts/analysisTools/tests/makeMtEfficiency.py
- scripts/analysisTools/w_mass_13TeV/plotPrefitTemplatesWRemnants.py
- scripts/histmakers/mw_lowPU.py
- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/histmakers/mz_dilepton.py
- scripts/histmakers/mz_lowPU.py
- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
- scripts/histmakers/w_z_gen_dists.py
- utilities/common.py
- utilities/common_lowPU.py
- utilities/output_tools.py
- wremnants/__init__.py
- wremnants/datasets/datagroups.py
- wremnants/datasets/datagroupsLowPU.py
Exploits new features in narf for saving and loading arbitrary python objects to hdf5 files, as well as H5PickleProxy object which allows lazy reading of objects even if embedded in dictionaries/lists/other objects.
> New hdf5-based io scheme with lazy reading of output histograms

- wremnants/theory_tools.py
The genWeight wasn't actually applied properly, which screwed up the MC normalisation.
> Fix bug where genWeight wasn't applied

- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/tests/biastests_step1.py
- scripts/tests/biastests_step3.py
- wremnants/muon_calibration.py
- This PR goes on top of PR182
- The smearing weights are updated such that additional axes can be added without breaking the code, this will be needed for the unfolding
> Smearing weights update

- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/tests/biastests_step1.py
- scripts/tests/biastests_step3.py
- wremnants/muon_calibration.py
- Fit to run with --onlyMainHistograms
- Update biastests
- Fix bug in muon calibration for closure bias
> Fit to run with --onlyMainHistograms; update biastests; fix bug in muon calibration for closure bias

- .github/workflows/main.yml
- scripts/ci/run_combine.sh
- scripts/ci/show_impacts.sh
- scripts/combine/setupCombineWMass.py
- scripts/combine/setupLowPU_Z.py
- scripts/histmakers/mw_lowPU.py
- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/histmakers/mz_dilepton.py
- scripts/histmakers/mz_lowPU.py
- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
- scripts/histmakers/w_z_gen_dists.py
- utilities/common.py
- utilities/output_tools.py
- wremnants/CardTool.py
first just for dilepton for a test, then will add others
> Add the combinetf fit to the CI

- .github/workflows/main.yml
- scripts/ci/run_combine.sh
- Fix CI that multiple datacards are used in the combine fit
- Add the "mode" option for the run_combine.sh script needed for unfolding
- Make a separate check for lowPU
> CI fix and update

- scripts/combine/studies/printConstraints.py
- scripts/combine/studies/runChargeDependentFits.sh
- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/studies/printImpactsAndConstraints.sh
a quick bugfix + edits in shell scripts that are not crucial to the common workflow
> hotfix for bug in mw histmaker

- .github/workflows/main.yml
- scripts/ci/show_impacts.sh
- scripts/ci/show_unfolded_results.sh
Not sure why but it's failing now. Mount still seems to work
> Revert use of eoscp

- scripts/ci/run_with_singularity.sh
In preparation for usage of Tensorflow Lite models in helpers.
> Update narf and singularity image version

- .github/workflows/main.yml
- scripts/ci/run_combine.sh
- scripts/ci/show_impacts.sh
Goal is to have the both the combined W+Z and the separate W fit. For now testing the possibility of having a step that depends on the result of other steps
> Testing the CI for combined fit

- .github/workflows/main.yml
- utilities/boostHistHelpers.py
- wremnants/CardTool.py
- wremnants/histselections.py
- wremnants/plot_tools.py
- wremnants/syst_tools.py
- wremnants/theory_tools.py
Separating out only the non-physics changes of #231
> Optimizations for hist operations

- .github/workflows/main.yml
This is likely what is responsible for the screwed up stat impacts
> Fixing scaling mistake in the CI

- wremnants/muon_efficiencies_smooth.py
Taken from the open PR of @cippy so we have a better record of the standalone impact. Marco let me know if this isn't the right description of the changes.
> Update smoothed 3D scale factors to use larger range of uT

- scripts/ci/run_with_singularity.sh
Needed for more flexible prefit/postfit plotting for the moment. 
Also fixes a critical bug for histogram conversion in some cases where one of the axes has size 1.
> Update narf and singularity image for combinetf2 and hist conversion fix

- .github/workflows/main.yml
Make sure that checkout is consistently configured for all steps.
> Fix lfs in ci (maybe)

- scripts/ci/run_with_singularity.sh
- scripts/plotting/unfolding_plots.py
As discussed in https://github.com/WMass/WRemnants/pull/290 this completes the integration of the updated Tensorflow build with Eigen symbol conflicts resolved.
(all other software are also updated to the latest available versions as well)
see https://gitlab.cern.ch/bendavid/cmswmassdocker/-/tree/v21?ref_type=tags
> update singularity image for ci

- README.md
Setting everything is not obvious for new users, so I augmented the readme with all passages.
I tested them on the cern machine, by they should work universally.
> update README with instructions to get combine and use it

- scripts/corrections/make_muon_response_maps.py
- scripts/corrections/make_resolution_corr.py
- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/histmakers/mz_dilepton.py
- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
- scripts/histmakers/w_z_muonresponse.py
- utilities/common.py
- wremnants/include/muon_calibration.h
- wremnants/muon_calibration.py
Still TODO:  add resolution uncertainties to the data cards/fit
> Update resolution corrections, add uncertainties to histmaker and enable by default

- .github/workflows/cleanup.yml
Seems like xrdfs can not delete recursively, this fix deletes the files and subfolders first
> Fix CI cleanup

- .github/workflows/main.yml
- .github/workflows/unfolding.yml
- wremnants/datasets/dataset_tools.py
> Make scheduled CI run over 1:1 data:mc events

- scripts/corrections/make_muon_response_maps.py
- scripts/histmakers/w_z_muonresponse.py
- wremnants/include/muon_calibration.h
Strategy for deriving muon response maps has been revised.
1) As a balance between accuracy and differentiability the interpolation of the cdf is reverted to a single step but the monotonicity requirement is dropped, resulting in a C2 continuous  cdf which is sufficient for deriving scale weights but not resolution weights.
2) An alternate response model is used to build the resolution weights, constructed from a "smoothed" resolution variation created by smearing the q/p for each muon 100 times when filling the response histogram.
> Update muon response maps and scale/resolution weights

- scripts/combine/setupCombine.py
- wremnants/CardTool.py
- wremnants/datasets/dataset_tools.py
1.  apply norm uncertainty to OOA splitting by charge
2. propagate helicity variations to OOA
> bugfixes to theory agnostic OOA

- wremnants/combine_theory_helper.py
Some details still being confirmed with scetlib authors on size and behaviour of the variations.
> add resummation matching transition variations back to fit

- scripts/utilities/check_root_files.py
Just adding a new utility script, to check if there's a corrupted file whenever a new production campaign is run.
I'll stop CI since this PR doesn't touch anything
> new file to check zombie root files before usage

- scripts/analysisTools/tests/testFakesVsMt.py
- wremnants/histselections.py
A small bug **wremnants/histselections.py** when integrateHighMT=True, since it was leading to a crash in my plotting script scripts/analysisTools/tests/testFakesVsMt.py
The comment in the script can be removed, I just wanted to understand whether I spotted another possible bug or whether the behaviour is the intended one. 
The changes in **scripts/analysisTools/tests/testFakesVsMt.py** don't need to be reviewed, it's just a plotting script whose only user so far was myself. I am just trying to make it more efficient and flexible (it also requires some possible updates of the W histmaker for tests, but since that part is not final and could be reverted I didn't commit them)
> small bug fix, and update script to run study of fakes

- .github/workflows/cleanup.yml
Let's see if this fixes the issue with the corrupted certificate
> Setup kerberos in cleanup CI workflow

- scripts/ci/run_with_singularity.sh
- scripts/combine/pullsAndImpacts.py
- scripts/combine/setupCombine.py
- scripts/plotting/makeDataMCStackPlot.py
- setup.sh
- utilities/boostHistHelpers.py
- utilities/io_tools/input_tools.py
- wremnants/CardTool.py
- wremnants/datasets/datagroups.py
- wremnants/muon_selections.py
- wremnants/plot_tools.py
- wremnants/syst_tools.py
- Option to normalise MC to data in plotting
- Some extensions for plotting systematics
- Some special keywords for syst groups to make --exclude and --keep easier to use
- Extend concatenateHists function to merge syst axes for future use in plotting
> Additions for plotting and nuisance exclusion

- scripts/analysisTools/plotUtils/utility.py
- scripts/analysisTools/w_mass_13TeV/diffNuisances.py
- scripts/analysisTools/w_mass_13TeV/getCorrelationLine.py
- scripts/analysisTools/w_mass_13TeV/makeSystRatios.py
- scripts/analysisTools/w_mass_13TeV/plotPrefitTemplatesWRemnants.py
- scripts/analysisTools/w_mass_13TeV/subMatrix.py
- scripts/utilities/browse_hdf5.py
Just some fixes/updates of some scripts, mainly in script/analysisTools/ to make prefit or postfit plots.
This PR should not change anything in the main analysis, but I had to share these changes with some people. CI could presumably be stopped to save resources, since I don't think it is aware of any of these scripts.
> Update plotting scripts

- scripts/analysisTools/tests/testPlots1D.py
- wremnants/datasets/datagroups.py
Useful when data process doesn't exist in the output of a histmaker (the default normalises MC to 1/fb), but even when data exist one might prefer to scale MC to some predefined value in plotting scripts.
> force lumi to any value to normalize MC 

- scripts/analysisTools/tnpPlotting/compareMCefficiency.py
- scripts/analysisTools/tnpPlotting/compareMass.py
- scripts/analysisTools/tnpPlotting/compareTnpMass.py
Just few plotting scripts to update, missed from the previously merged PR #417 
I will kill CI jobs since nothing else is modified that is relevant for the code run in CI
> update a few plotting scripts

- scripts/analysisTools/tnpPlotting/compareMCefficiency.py
- scripts/analysisTools/tnpPlotting/compareMass.py
- scripts/analysisTools/tnpPlotting/compareTnpMass.py
- scripts/analysisTools/tnpPlotting/plotYieldsEtaPt.py
- scripts/analysisTools/w_mass_13TeV/makeImpactsOnMW.py
Just minor updates in few scripts stored in **scripts/analysisTools/tnpPlotting/** , and a new script to plot yields vs eta-pt.
> Updating plotting scripts for TnP output

- .github/workflows/main.yml
- .github/workflows/unfolding.yml
- scripts/histmakers/mw_lowPU.py
- scripts/histmakers/mz_dilepton.py
- scripts/histmakers/mz_lowPU.py
- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
- wremnants/Templates/index.php
- wremnants/datasets/datagroups.py
- wremnants/datasets/dataset_tools.py
- changing the dataPath in the CI to run on files locally since running on files on eos showed occasionally issues 
- using the new index.php from cat tools (https://cms-analysis.docs.cern.ch/guidelines/other/plot_browser/)
> Change dataPath to run on files locally

- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/recoil/exportHists.py
- scripts/recoil/functions.py
- scripts/recoil/makePlots.py
- scripts/recoil/met_xy_reweighting.py
- utilities/common.py
- utilities/styles/nuisance_translate.json
- utilities/styles/styles.py
- wremnants/combine_helpers.py
- wremnants/recoil_tools.py
- Added calibrations for DeepMETPVRobust and DeepMETPVRobustNoPUPPI
- Updated calibrations for RawPFMET and DeepMETReso (old DeepMET) - for consistency
- Statistical uncertainties defined for all 4 MET definitions (no systematics for now)
- Switched to DeepMETPVRobust as default MET - will change central values of data and MC
> Updates of recoil calibration highPU

- .github/workflows/main.yml
- .github/workflows/unfolding.yml
- scripts/combine/setupCombine.py
- scripts/plotting/fakerate.py
- scripts/plotting/makeDataMCStackPlot.py
- scripts/plotting/plot_decorr_params.py
- scripts/plotting/postfitPlots.py
- utilities/boostHistHelpers.py
- wremnants/datasets/datagroups.py
- wremnants/datasets/datagroups2016.py
- wremnants/datasets/datagroupsLowPU.py
- wremnants/histselections.py
- wremnants/plot_tools.py
- Update fake estimation to extended 1D method, smoothing in pT
- Include a global correction factor of 1/1.15 to scale the fake estimation based on the nonclosure from QCD MC
- Include a fake normalization uncertainty of 15% based on the global correction
- Update the mass decorrelation plot
- Small updates & fixes on the fake estimations
> Update fake estimation to extended 1D

- .github/workflows/main.yml
- .github/workflows/unfolding.yml
- scripts/combine/setupCombine.py
- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/histmakers/mz_dilepton.py
- scripts/histmakers/w_z_gen_dists.py
- scripts/plotting/fakerate.py
- scripts/plotting/makeDataMCStackPlot.py
- scripts/plotting/postfitPlots.py
- scripts/plotting/response_matrix.py
- scripts/plotting/unfolding_massbias.py
- scripts/plotting/unfolding_xsec.py
- scripts/utilities/fitresult_pois_to_hist.py
- utilities/common.py
- utilities/io_tools/conversion_tools.py
- wremnants/combine_helpers.py
- wremnants/combine_theory_helper.py
- wremnants/datasets/datagroups.py
- wremnants/datasets/dataset_tools.py
- wremnants/muon_selections.py
- wremnants/syst_tools.py
- wremnants/theoryAgnostic_tools.py
- wremnants/theory_tools.py
- wremnants/unfolding_tools.py
- Updates to convert & store unfolded results in a pickle file
- Updates on gen histmaker
- In dataset_tools, apply filter and exclusion functionality before scanning the files since it's not necessary and reduces the amount of printout
- rename "csSineCosThetaPhi" to "csSineCosThetaPhigen" since having a column with the same name as a function led to problems when calling the function
- Fix bin width norm in plots, only apply bin width norm in case of variable binning and change label from "Events/bin" to "Events/unit" in case events are divided by bin width
- Fix quark mass uncertainties
- Reduce scale of EW virtual variations from 2 to 1
> Converting/storing unfolding results; miscellaneous

- scripts/combine/setupCombine.py
- wremnants/CardTool.py
- Fix running with --excludeProcGroups Fake (previously crashed because fake syst uncertainty was always added and passSystToFakes was False even if --excludeProcGroups Fake was given)
- Fix --pseudoDataFile for wmass (previously no hist selection was performed on pseuodata from extra file)
- Fix --pseudoData for root output (previously pseudodata was overridden with asimov)
> Some small fixes

- wremnants/muon_selections.py
The change for the heavy flavour control region should be modest, since just the muon-SV matching is improved by using match-by-index instead of deltaR.
The prompt suppression in the light flavour control region should be much better since now the kink finder is explicitly inverted.
> improve fake control region definitions

- utilities/common.py
- wremnants/combine_theory_helper.py
- wremnants/plot_tools.py
plus minor fix to gen binning and small plotting script changes
This is a more minimal version of https://github.com/WMass/WRemnants/pull/454 (and replaces it for the moment)
> Use SCETlib alphas unc by default 

- wremnants/Templates/index_mit.php
- wremnants/plot_tools.py
Updated php file for MIT usage:
1. Added a new, MIT-usable php file, from Jan.
2. Updated the plot_tools.py file to check if user is MIT. Then, it copies the appropriate php file to output.
> Add index_mit.php option, and automatically use it if running at MIT

- scripts/combine/setupCombine.py
- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/recoil/exportHists.py
- scripts/recoil/functions.py
- scripts/recoil/makePlots.py
- scripts/recoil/met_xy_reweighting.py
- scripts/recoil/plotter.py
- scripts/recoil/plotutils.py
- scripts/recoil/vpt_reweighting.py
- wremnants/combine_theory_helper.py
- wremnants/include/recoil_helper.h
- wremnants/include/recoil_tools.h
- wremnants/recoil_tools.py
Updated recoil calibration for 4 highPU MET estimators
Small fix for PDF inflation factor from the command line
> Updated recoil calibration

- scripts/combine/pullsAndImpacts.py
- scripts/corrections/make_theory_corr.py
- scripts/corrections/plot_theory_corr.py
- scripts/plotting/controlPlotsHDF5.py
- scripts/plotting/covariance.py
- scripts/plotting/fakerate.py
- scripts/plotting/makeDataMCStackPlot.py
- scripts/plotting/plot_angular_coefficients.py
- scripts/plotting/plot_decorr_params.py
- scripts/plotting/postfitPlots.py
- scripts/plotting/response_matrix.py
- scripts/plotting/roc_curve.py
- scripts/plotting/unfolding_plots.py
- scripts/plotting/unfolding_xsec.py
- scripts/tests/plot_GoF.py
- scripts/utilities/print_command.py
- utilities/io_tools/combinetf_input.py
- utilities/io_tools/input_tools.py
- utilities/io_tools/output_tools.py
- utilities/io_tools/tex_tools.py
- utilities/styles/styles.py
- wremnants/datasets/datagroups.py
- wremnants/plot_tools.py
- Update eoscp functionality to create a unique folder in /tmp using the [tempfile](https://docs.python.org/3/library/tempfile.html) library instead of creating a "temp" folder in the working directory. The old implementation had some issues: if the script is not running through files remain in the "temp" folder, also, when running two plotting scripts from the same working directory they can interfere and cause crashing the script. 
- Given that the temporary folder has a unique, previously unknown name, it is now required to specify this path in the ```output_tools.copy_to_eos``` function. There are some notebooks and scripts that need to be adapted. 
- Update plots and utilities
> Update eoscp functionality and miscellaneous

- .github/workflows/unfolding.yml
- scripts/combine/pullsAndImpacts.py
- scripts/combine/setupCombine.py
- scripts/histmakers/mw_with_mu_eta_pt.py
- scripts/histmakers/mz_wlike_with_mu_eta_pt.py
- scripts/plotting/controlPlotsHDF5.py
- scripts/plotting/inclusive_xsec_summary.py
- scripts/plotting/plot_angular_coefficients.py
- scripts/plotting/plot_harmonic_polynomials.py
- scripts/plotting/postfitPlots.py
- scripts/plotting/response_matrix.py
- scripts/plotting/unfolding_xsec.py
- scripts/utilities/fitresult_pois_to_hist.py
- utilities/common.py
- utilities/io_tools/conversion_tools.py
- utilities/styles/styles.py
- wremnants/HDF5Writer.py
- wremnants/combine_helpers.py
- wremnants/theoryAgnostic_tools.py
- wremnants/unfolding_tools.py
This is a part of PR #445 that should not change the results
- Adding/updating a few plotting scripts
- Simplification/ clean up of code
- Adding some functionality in preparation for linearized unfolding
- The most notable change for users is that the genAxes argument in the setupCombine.py is now a list of dashed separated strings for the axes names, similar to the fit axes, in order to make a card from different input files with different gen axes
> Updates on unfolding

- wremnants/histselections.py
- Previously the systematic histograms for the fakes from the smoothing parameters were not correct. Only the diagonal elements in up/down and parameter axes were set to the alternate histograms while the off-diagonal elements were empty (but should be the nominal values). This is not expected to lead to a change since luckily due to the symmetrization in the CardMaker/HDF5Writer these zeros in the off-diagonal elements are set to the nominal.
> Fix systematic variations of fakes

- scripts/ci/run_with_singularity.sh
Only minor changes/additional packages so there should be no impact on anything.
> Update singularity image to v29

- wremnants/Templates/index.php
Fix an issue in the plot browser index.php from CAT due to a security vulnerability (see https://cms-talk.web.cern.ch/t/security-advisory-php-plots-action-needed/46432)
> Fix security issue in index.php

- scripts/plotting/postfitPlots.py
- utilities/styles/styles.py
- wremnants/plot_tools.py
- update narf to support computing postfit histograms with noi variations with narf/scripts/fitting/combinetf2.py (using --computeNOIVariations)
- support plotting postfit noi variations with scripts/plotting/postfitPlots.py (using --noiVariation)
- supporting plotting log scale y-axis (currently default only for 1D plots)
- support log transformed plots and differences instead of ratios with scripts/plotting/postfitPlots.py
> Update postfit plotting

- scripts/plotting/controlPlotsHDF5.py
- scripts/plotting/makeDataMCStackPlot.py
- scripts/plotting/plot_decorr_params.py
- scripts/plotting/postfitPlots.py
- scripts/plotting/unfolding_plots.py
- scripts/plotting/unfolding_xsec.py
- utilities/common.py
Fixing some small bugs in the plotting scripts introduced in the previous update
> Updetes on plotting scripts

- scripts/ci/run_with_singularity.sh
Updated singularity image to v30 (the only change is that hepdata-tools python package has been added so this shouldn't make any difference for the ci)
> update singularity image

- scripts/histmakers/mw_with_mu_eta_pt.py
- wremnants/__init__.py
Technical updates to support newer ROOT, python, tensorflow versions.
In preparation for an upcoming update to the singularity image.
No changes expected in the CI
> Technical updates

- scripts/ci/run_with_singularity.sh
- scripts/histmakers/mw_lowPU.py
- scripts/histmakers/mw_with_mu_eta_pt.py
- utilities/styles/styles.py
- wremnants/lowpu.py
- wremnants/syst_tools.py
Major upgrades to python, tensorflow, ROOT
ROOT is now built with C++20 support as well (and jitted code should be processed in C++20 mode by default)
> update singularity to v34

- scripts/plotting/make_postfit_vgen.py
- scripts/plotting/response_matrix.py
This fixes a small bug in a plotting script making the high stat unfolding CI working again
> Fix unfolding CI (high stat)

- .github/workflows/main.yml
- scripts/ci/run_with_singularity.sh
The CI currently fails for unknown reasons. This PR fixes the issue by 
- Using a cache dir instead of a file
- Doing the kinit only outside the singularity and using it inside
Although, I don't really understand why it fixes the issue.
> Update kerberos credentials in singularity

- scripts/combine/setupCombine.py
- wremnants/datasets/datagroups.py
For the purpose of statistical tests.
This also includes a technical fix to narf to avoid unnecessarily setting TF threading environment variables which slow things down on multicore machines.
> Add functionality to absorb systematics into data covariance matrix.

- scripts/analysisTools/tests/checkFitHDF5.py
- utilities/styles/styles.py
- wremnants/combine_theory_helper.py
In this way we can check them whenever we want
> Save grouped impacts split by angular coefficients
