WMass/WRemnants

scripts/combine/fitManager.py
scripts/combine/setupCombineWMass.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
wremnants/syst_tools.py

Remove "Iso" from effSystIsoTnp_xxx nuisance, since iso or not iso depends on the xxx part of the name, this also makes it consistent with effStatTnP.
The rest is just an update for my script to manage card combination and fit (but I would invite people to use it too if they like)
Small fixes for QCD scales binned by pt (mainly remove unnecessary arguments used when the input histogram was still the one with helicity splitting).
Add possibility to rebin the axis with gen Vpt when setting up the cards.

Change name of effSyst nuisance, fix for QCD scales, and update my script to manage fit

---

scripts/combine/fitManager.py
scripts/combine/setupCombineWMass.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
wremnants/CardTool.py
wremnants/datasets/datasetDict_v9.py
wremnants/include/histoScaling.h
wremnants/include/utils.h
wremnants/theory_tools.py

**mw_with_mu_eta_pt.py**
- add gen match for top background (only W for now)
- add ECAL prefiring weights and corresponding syst hists
**setupCombineWmas.py** and **CardTool.py**
- add QCD scales and other signal systs to tau
- add stat unc on fakes (was default but removed by mistake)
- fix removal of systs from fakes (was mistakenly modifying input list of processes on which to apply the syst)
- add groups of nuisances to card for charge plus (was being written only for charge minus)
- add ECAL prefiring weights and related syst
- improve naming of effStat nuisance parameters and fix wrong scaling by sqrt(2) (it was scaling trigger rather than isolation)
**wremnants/theory_tools.py**
- fix alphaS histogram, was missing nominal event weight
**TODO**:
- add missing QCD scales for Z when …

Bug fixes and updates for histogram and card maker

---

scripts/combine/setupCombineWMass.py
utilities/boostHistHelpers.py
wremnants/CardTool.py
wremnants/pileup.py

- fixing small bug for PU weights (clipping of large weight was not applied, but had no effect for postVFP since weights are never very large)
**setupCombineWmass.py**
- add option --noHist to skip saving 2D histograms in file (it makes sense only if the file already exists and for some reason one doesn't want to fill it again), which might make the code slightly faster, although the slowest part is about reading boost histograms for the pickle file and this can't be avoided, because systs to write in the card are somehow derived from those.
- augment domain of option --excludeNuisances, allowing to skip the reading of some boost histograms, e.g. with -x ".*pdf.*" to skip the pdf histogram entirely.

Some fixes and new features for card maker

---

scripts/combine/fitManager.py
scripts/combine/setupCombineWMass.py
scripts/histmakers/mw_with_mu_eta_pt.py
wremnants/CardTool.py
wremnants/datasets/datagroups.py
wremnants/include/vertex.h

Adding syst for fakes, obtained varying the awayJet pt from the nominal 30 GeV to 45. The new histogram is added in the hist maker, and in setupCombineWmass.py it is mirrored to define a shape uncertainty (actually the mirroring doesn't make much sense for this syst, because it is one way by definition, so it should be changed).
The effect is mostly flat vs eta, but with a shape variation vs pt for the QCD template, from +20% of nominal at low pt down to few % at high pt.
Also implementing a fix for CardTool.py,  adding a space before the "shape" keyword in the datacard, otherwise when a syst has a very long name the syst name and the keyword were chained with no separation, causing error when trying to run the fit or combine cards.

Add new shape systs for fakes, and a bug fix for CardTool.py

---

wremnants/include/lowpu_rochester.h

PR to replace the erf and inverted erf functions with the TMath functions, to avoid compiling issues in boost libraries. Tested and confirmed the results from TMath are consistent with boost.

replace boost Erf with TMath Erf

---

wremnants/include/muon_calibration.h
wremnants/muon_calibration.py

Add some helpers used in muon calibration-related scripts (to be added in later PRs)
Bump narf mainly for improvements to the tensorflow fitter
@jeyserma this should now give the correct uncertainties for nll fits with weighted events (as long as the variance is consistently present in the histogram)

Add helpers for calibration workflows and bump narf for fitter improvements

---

setup.sh

Major robustness improvements to hdf5-based io, which unfortunately breaks backwards compatibility with hdf5 files produced using the initial version.  (but at least a sensible error message should be given since protocol versioning is being written to the files in all cases)
narf is now also silencing tensorflow warnings via environment variables set in the setup script.  In order for this to correctly take effect in WRemnants as well the setup script has been improved to call the narf setup script rather than adding it to the PYTHONPATH directly.
A bug was also fixed in setting the WREM_BASE environment variable when the setup script was being called from an external location.

Technical improvements

---

wremnants/__init__.py

There is a major conflict between tensorflow and Eigen:
The .so files which are loaded when calling ```import tensorflow``` export some symbols from Eigen which may not be of the same version or compiles with the same preprocessor directives as what is being jitted with cling.
In particular this concerns ```Eigen::internal::TensorBlockScratchAllocator<Eigen::DefaultDevice>::allocate``` which can lead to invalid calls to free (memory addresses mismatched from the corresponding malloc due to inconsistent alignment adjustments to the pointer address).
For the moment avoid importing tensorflow by default in narf, and add explicit protections such that a sensible error is printed rather than a segfault or other undefined behaviour.

Avoid conflicts between tensorflow and Eigen

---

scripts/analysisTools/plotUtils/utility.py
scripts/analysisTools/tests/testFakesVsMt.py
scripts/analysisTools/tests/testQCDisoMtCorr.py
scripts/analysisTools/tests/testShapesIsoMtRegions.py
scripts/analysisTools/w_mass_13TeV/plotPrefitTemplatesWRemnants.py
scripts/combine/setupCombineWMass.py
utilities/input_tools.py
wremnants/CardTool.py
wremnants/histselections.py

The canvas popup was related to importing some functions from script/analysisTools/plotUtils/utility.py, where a leftover canvas was defined in the global scope.
The canvas creation has now be moved in a local scope, but also the imported functions are now moved to utilities/input_tools.py
They are safeOpenRootFile and safeGetRootObject, which are used to read the mT correction for fakes from a root file in CardTool.py
Also, this PR removes the annoying warning messages appearing in CardTool.py when doing efficiency histograms for Wmass for the wrong reco charge. There is a check to warn when the histogram ratio var/nomi is exactly 1, but this is expected to happen for efficiency histograms, since the tensor also has the reco charge.
CardTool.addSystematics now has a …

Fix canvas popup, and silent warning messages from efficiency histograms in CardTool

---

scripts/histmakers/mw_lowPU.py
scripts/histmakers/mz_lowPU.py
scripts/lowPU/recoilCorrection.py
wremnants/__init__.py
wremnants/correctionsTensor_helper.py
wremnants/include/muon_efficiencies_binned_vqt.h
wremnants/muon_calibration.py
wremnants/muon_efficiencies_binned.py
wremnants/muon_efficiencies_binned_vqt.py
wremnants/muon_efficiencies_binned_vqt_integrated.py
wremnants/muon_efficiencies_binned_vqt_real.py
wremnants/muon_efficiencies_smooth.py
wremnants/muon_prefiring.py
wremnants/muon_validation.py
wremnants/pileup.py
wremnants/recoil_tools.py
wremnants/theory_tools.py
wremnants/vertex.py

New function ```narf.clingutils.Declare``` wraps ```ROOT.gInterpreter.Declare``` and checks the return code, raising an error if the compilation fails.  Previously compilation errors could go unnoticed and lead to crashes later on.

Move to updated narf with safe version of Declare

---

.github/workflows/main.yml
scripts/histmakers/mz_dilepton.py
scripts/plotting/makeDataMCStackPlot.py
wremnants/datasets/datagroups.py
wremnants/plot_tools.py

The use of the 3D histograms makes the dilepton combine step super slow. We really only need them 1D for plotting, so this PR adds them as 1D hist regardless of which you choose. The --axes option is still used for the nominal hist + uncertainties.
Also update the CI accordingly. Because the variation hists aren't made for these additional hist, switch to using the corrected theory distribution as the nominal in the CI plotting, with MiNNLO uncorr plotted as a variation.
Also remove the QCD MC from the W plots
Reopened from #176 because I don't understand why the CI isn't running

Fixes to CI plotting

---

wremnants/datasets/datasetDict_v9.py

Added missing ST_tW_top_5f_NoFullyHadronicDecays sample for top, and moving to exclusive decays for diboson (so far we only had ZZ). Cross sections have also been updated almost everywhere for top samples. 
This should also finally solve the long standing issue here: https://github.com/WMass/WRemnants/issues/14
This PR is presumably not urgent, although I would move to it as soon as possible, since the changes are not negligible and might be even more important for fakes.
This is **not backward compatible**, since any script we have to get our histogram reads the processes' names from the datagroups based on what's found in this file, so as soon as this is merged everybody should just rerun all histograms.
**Note**: new samples currently stored in /scratch/shared/NanoAOD/BKGV9/ on the …

updating top and diboson samples, fixing cross sections too

---

.github/workflows/main.yml
scripts/combine/pullsAndImpacts.py
scripts/plotting/makeDataMCStackPlot.py
scripts/plotting/makePdfUncPlot.py
wremnants/muon_calibration.py
wremnants/plot_tools.py

This was screwing up a subset of the systematics hists, notably the mass shift, which totally screws up the impacts.
Originally introduced in #183 so any studies done in the meantime should be repeated.
Also added a bit more to the CI, including plots of the mass variation, to catch such mistakes

Fix nasty bug where nominal cols were accidentally modified

---

scripts/histmakers/w_z_gen_dists.py
wremnants/datasets/datasetDict_v9.py
wremnants/include/csVariables.h
wremnants/include/theoryTools.h
wremnants/theory_tools.py

- The lepton and anti lepton were interchanged in the prefsr definition. At other places, they were interchanged a second time, I hope I found all occurrences, but please check.
- Sample path for one of the new samples was missing one "/*" as seen by the warnings

Fix mix up of prefsr lepton definition; fix sample path

---

scripts/combine/setupCombineWMass.py

This PR builds on top on the current main branch, and removes the systematic uncertainty on the fakes for the mt dependence. After the deltaPhi cut the mt correction is flat around unity (i.e. no dependence), so it is no longer needed.

remove syst for mt dependence on fakes

---

scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
utilities/common.py

This singles out the removing of underflow and overflow bins in the histmaker (Was previously previously in #212). 
- Remove overflow and underflow bins in main axes by default; Given the bins in the mw_with_mu_eta_pt histmaker this reduces the bins from ```31*50*2*2 = 6200``` to ```29*48*2*2 = 5568``` bins, a reduction of ~10%. 
- By default the underflow/overflow is included, a command line argument is added for excluding them

Remove overflow and underflow bins in main axes

---

.github/workflows/main.yml
scripts/combine/setupCombineWMass.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_lowPU.py
scripts/histmakers/w_z_gen_dists.py
utilities/boostHistHelpers.py
utilities/common.py
wremnants/CardTool.py
wremnants/combine_helpers.py
wremnants/syst_tools.py
wremnants/theory_tools.py

Some fixes for the current theory implementation such that the NP and scetlib uncertainties are (probably) consistently propagated to both the mw and wlike fits.
The pt-helicity decorrelated scale variations have also been made the default, with the overlaps ~properly removed with respect to the scetlib uncertainties (sigma_-1 is varied only at high pt, and all the other helicity components are varied over the full pt range)

Theory fixes

---

scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_lowPU.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
utilities/common.py
wremnants/include/muon_efficiencies_smooth.h
wremnants/include/utils.h
wremnants/recoil_tools.py

For consistency, this is now also implemented for the high PU wlike analysis.
I didn't add it to low PU analysis flows because I am not sure we want the same cut, or with the same threshold.
The threshold is configurable with the same option that was in the mw histmaker, now moved to utilities/common.py to be used also for the mz_wlike histmaker
I also renamed the function to compute the wlike transverse mass with a more sensible name, and changed that everywhere. There are also a couple of new function to create the wlike met, which can then be reused directly (also for mT but not only).

adding deltaPhi(mu,met) also for Wlike using wlikeMET

---

utilities/boostHistHelpers.py

Names were not moved in the same way as indices. While in the `np.moveaxis` function -2 means second to last index, in `insert` function for a list -1 means second to last index. 
For some reason the previous code did not break but when the reco charge axis is removed then the code broke. 
Presumably, the gen V charge was used instead of the reco charge before, which has the same dimension.

Fix bug in envelope calculation 

---

wremnants/muon_efficiencies_smooth.py

Just a stupid bug from a previous PR, it was causing the last bin of the eta-decorrelated effsysts to miss

fix bug skipping last bin for decorrelated effsyst

---

wremnants/CardTool.py

As for the title, this PR ensures that there is always 1 space between process names in datacard.
Before, the space allotted for each process was configured, but since we can't predict the length of process names we were forced to use unnaturally large spacing, which may have still not been sufficient (it happened to some of us). 
This also allows us to keep the available space for each process name to a reasonable minimum, to avoid having absurd datacard with fields separated by enormous white spaces when not necessary.

fix for space between process name in datacard

---

scripts/combine/Templates/WMass/main.txt
wremnants/CardTool.py

- Write relative paths in the text datacards instead of absolute paths (for better practical use)
- Write shapes into sub folders in root file, this speeds up the text2hdf5.py

Update writing datacards

---

wremnants/datasets/datagroups.py
wremnants/histmaker_tools.py

In the current main to run the histmaker w/o data one needs to specify ```--noScaleToData```. This PR allows to run w/o this specification by simply assigning lumi=1 if no data is given.

Make it possible to run w/o data without specifying additional CL args

---

utilities/boostHistHelpers.py

For addHists I am adding two parameters scale1 and scale2, to apply a multiplicative constant factor to any of the two inputs (one use case was to do x -y, scaling the second by -1, but I made it general).
I could have had a single argument accepting a pair, but I think this is simpler and easier for the user.
For the ratio, I just wanted to allow setting the value for special cases like 0/0, it was 1 so far, but if the ratio represents an efficiency the case 0/0 means no events at denominator, so the efficiency can be assumed to be 0.
About the condition for the cutoff, this currently assumes that the factors are expected to be positive, which may not always be the case. It was true for any use case I had so far, though.
Perhaps one may extend the condition to different configurations …

add features to addHists and fix possible bug in other functions

---

scripts/combine/setupCombineWMass.py
utilities/common.py
wremnants/syst_tools.py

Weights for different W or Z boson widths are stored in the ntuples (branch "MEParamWeightAltSet1"). In this PR the weights are propagated in the histmaker and cardmaker to assess the corresponding uncertainty.

Add width uncertainty on W and Z

---

scripts/histmakers/mw_lowPU.py
scripts/plotting/makeDataMCStackPlot.py
utilities/boostHistHelpers.py
wremnants/CardTool.py
wremnants/datasets/datagroups.py
wremnants/datasets/datagroupsLowPU.py
wremnants/histselections.py

Axes to be integrated in the fakerate computation can be specified. Mainly to improve the fakerate estimation for mtW and ptll in lowPU. The histogram broadcasting needed to be adjusted to be able to deal with missing inner dimensions since the fakerate may not have missing inner dimensions when systematics are computed.

Fakerate based on lepton pt eta charge

---

README.md
scripts/analysisTools/plotUtils/utility.py
scripts/analysisTools/w_mass_13TeV/diffNuisances.py
scripts/analysisTools/w_mass_13TeV/makeImpactsOnMW.py
scripts/analysisTools/w_mass_13TeV/plotPrefitTemplatesWRemnants.py
scripts/analysisTools/w_mass_13TeV/subMatrix.py
scripts/combine/setupCombineWMass.py
wremnants/combine_theory_helper.py

There was already option --scaleTNP to achieve that, but it was not propagated to the datacards. This PR implemented that.
The only relevant files that are modified are:
- **scripts/combine/setupCombineWMass.py**
- **wremnants/combine_theory_helper.py**
The rest is just a set of plotting scripts that don't affect the main analysis.
I checked that the scaling factor is correctly propagated to the datacards for the mW fit (default is 1, namely no scaling).

Scale resumTNP nuisances in CardTool

---

scripts/utilities/browse_hdf5.py

Some people including myself expressed the interest in having a simple interface to browse an hdf5 file to explore its content, given that it's not as trivial as opening a root file and doing ".ls".
I hope it helps.
This PR overrides PR#272, which I've already closed.
It also implements the comments received in the previous PR, about using sub_parsers to  avoid inconsistent options that are only valid when other are called.
Examples:
- python scripts/utilities/browse_hdf5.py input.hdf5 proc
- python scripts/utilities/browse_hdf5.py input.hdf5 hist -p Diboson -a eta
- python scripts/utilities/browse_hdf5.py input.hdf5 hist -p Top --noAxes
- python scripts/utilities/browse_hdf5.py input.hdf5 hist -p Top -n nominal_effSystTnP

new script to browse content of hdf5 files

---

scripts/combine/fitManager.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
scripts/lowPU/MET_xy_correction.py
scripts/lowPU/functions.py
scripts/lowPU/makePlots.py
scripts/lowPU/qT_reweighting.py
scripts/lowPU/response_mt.py
scripts/recoil/exportHists.py
utilities/common.py
wremnants/combine_helpers.py
wremnants/include/lowpu_recoil.h
wremnants/include/recoil_helper.h
wremnants/muon_selections.py
wremnants/recoil_tools.py
wremnants/theory_corrections.py

Implemented the DeepMET recoil calibration with uncertainties using the TFLite model. Currently, by default, the recoil uncertainties are switched OFF, as they take a lot of time to run. In a next PR, we'll address the performance issue. The central correction is applied regardless. So run with recoil uncertainties, use the option --recoilUnc
Added option to run the analysis without theory corrections: --theoryCorr none

DeepMET recoil calibration with uncertainties

---

wremnants/datasets/datasetDict_v9.py
wremnants/datasets/dataset_tools.py

After creating symlinks so the new samples have the expected format with the TrackFit and NanoProd tags, they can simply be added. With the current setup they will be skipped, with a warning message, when running from /scratch at lxplus8s10, and will be included when using --dataPath /eos/cms/store/cmst3...
A warning message is printed in the case where they aren't found (e.g., running from scratch). At MIT/Pisa this technically should work but reading from eos will be way slower.
TODO: We should implement a mode to load all the samples but only process up to a max number of events. We could probably also just set the default maxfiles to large number in the meantime

Add new datasets using symlinks

---

.github/workflows/main.yml
scripts/analysisTools/tests/testFakesVsMt.py
scripts/analysisTools/w_mass_13TeV/makeImpactsOnMW.py
scripts/analysisTools/w_mass_13TeV/smoothLeptonScaleFactors.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/plotting/makeDataMCStackPlot.py
wremnants/datasets/datagroups2016.py

The histogram used to plot mT was not appropriate for the computation of the fakes, because it didn't have eta-pt axes.
Instead of adding those axes to the current transverseMass histogram, making it quite bigger, I would propose reusing the histogram mTStudyForFakes which has all axes and is already available.
However, it has additional axes which must be integrated out for the plot, so this PR add a new option to **scripts/plotting/makeDataMCStackPlot.py** to achieve that (it reuses existing features of datagroups to manipulate histograms through some sort of selection).
From a local test I got these histograms [0], identical to those I make with independent scripts.
I would also suggest making the plots splitting by charge since they are not necessarily identical, which requires using …

Attempt to fix mt  plot in CI for Wmass

---

README.md
scripts/analysisTools/plotUtils/utility.py
scripts/analysisTools/tests/testShapesIsoMtRegions.py
scripts/analysisTools/w_mass_13TeV/makeImpactsOnMW.py
scripts/analysisTools/w_mass_13TeV/makeRatioTH2.py
scripts/analysisTools/w_mass_13TeV/makeSystRatios.py
scripts/analysisTools/w_mass_13TeV/plotTemplateWithAi.py
scripts/combine/fitManager.py
scripts/combine/setupCombine.py
scripts/combine/setupCombineWMass.py
scripts/histmakers/mw_with_mu_eta_pt.py
utilities/differential.py
wremnants/CardTool.py
wremnants/datasets/datagroups.py
wremnants/helicity_utils.py
wremnants/muon_efficiencies_smooth.py

First implementation, which exploits the same code that was previously developed for the original theory agnostic fit. A new option --poiAsNoi is added, to be used in conjunction with previous --theoryAgnostic.
This creates a new systematic histogram with the cross section (event yields) binned in W pt-y-Ai (essentially it is the nominal histogram of the original theory agnostic fit). Other than that, the histmaker works exactly as in the traditional mW analysis, with all the currently implemented systematics.
Then, in setupCombineWmass.py this new histogram is summed to the nominal of the traditional analysis to form a histogram with the actual cross section variation in each bin with respect to the nominal itself. A new option --priorNormXsec is added to set the value of the prior in …

Theory agnostic fit with POI as NOI

---

.github/workflows/main.yml
scripts/analysisTools/w_mass_13TeV/makeImpactsOnMW.py
scripts/analysisTools/w_mass_13TeV/makeRatioTH2.py
scripts/combine/setupCombine.py
scripts/histmakers/mw_lowPU.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/w_z_gen_dists.py
scripts/plotting/response_matrix.py
wremnants/CardTool.py
wremnants/datasets/datagroups.py
wremnants/include/utils.h
wremnants/theory_tools.py

This PR updates the theory agnostic setup with POI as NOI, by adding the possibility to split signal into in-acceptance (IA) and out-of-acceptance (OOA). This is the only way to allow some systematics to be propagated only to one part (e.g. theory ones). 
Consequently, the naming of the OOA template in the card is modified (using current features of datagroups to define a new group BkgWmunu including only the OOA).
To work, one has to use --separateOOAfromSignal when running the W histmaker. 
This PR also includes a fix to a bug, which was filtering away OOA events from the previous implementation (thus signal was only the IA when running with --theoryAgnostic --poiAsNoi)
One thing that is still missing is the possibility to assign a norm uncertainty on the OOA (either when split from IA …

Developments for theory agnostic and few other things

---

wremnants/helicity_utils.py

As discussed on MM, there was a bug when reading the angular coeff histograms produced from the gen scripts. PR aims to fix this. 
##Test: 
The following runs successfully. 
```python WRemnants/scripts/histmakers/mw_with_mu_eta_pt.py -v 4  --noRecoil --onlyMainHistograms --muonCorrMC none --muonCorrData none --noScaleFactors --maxFiles 2 --theoryAgnostic --filterProcs Wplusmunu```

Bug-fix reading angular coeff histograms

---

scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
utilities/common.py

The weights were missing completely from Wlike and dilepton analyses.
This PR also reshuffles some of the other weights in the global expression of the event weight to make the flow more aligned with the W histmaker.
Also adding the option to remove SF (mainly for tests), which was only in the W histmaker. This option was moved to utilities/common.py in the scope for high PU, but it might eventually be extended to low PU too.

implement vertex z weights for Z analyses

---

.gitmodules
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/w_z_gen_dists.py
scripts/plotting/makePdfUncPlot.py
utilities/differential.py
utilities/io_tools/output_tools.py
wremnants/__init__.py
wremnants/helicity_utils.py
wremnants/include/csVariables.h
wremnants/include/syst_helicity_utils.h
wremnants/include/theoryTools.h
wremnants/include/theory_corrections.h
wremnants/syst_tools.py
wremnants/theoryAgnostic_tools.py
wremnants/theory_tools.py

This builds on top of (and replaces) https://github.com/WMass/WRemnants/pull/310
The updated definition of the Ai's and helicity cross sections and other additions are maintained, but the angular terms and moments are factorized in such a way that 9 elements can be used everywhere for the corresponding helicity tensors.
The scaling and offsets to convert from moments to angular coefficients have been moved into the C++ code as part of this change, which significantly simplifies the corresponding python function.

Updates to Ai definitions, plotting and uncertainties on Ai's/helicity cross sections

---

scripts/histmakers/mz_dilepton.py
utilities/io_tools/output_tools.py

The current validation histograms in the dilepton histmaker are supposed to be used when running the actual dilepton trigger selection (which is not the default in any case). 
Also, when running with --maxFiles != None the number is appended to the output file name for convenience (typical use case was when running with few files for tests while avoiding overriding other possible existing files). However this is annoying when the argument to --maxFiles is negative, also because with the full stat one doesn't want any additional tag on the name, so now this is appended only when positive.
If requested, I could implement the appending of "fullStat" when "--maxFiles -1"
This PR doesn't change anything to the physics, and was tested locally.

Minor fixes about histmaker output file name and dilepton validation histograms

---

scripts/histmakers/mw_lowPU.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_lowPU.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
scripts/histmakers/w_z_gen_dists.py
wremnants/CardTool.py
wremnants/combine_theory_helper.py
wremnants/helicity_utils.py
wremnants/include/theoryTools.h
wremnants/include/theory_corrections.h
wremnants/syst_tools.py
wremnants/theory_corrections.py
wremnants/theory_tools.py

MiNNLO scale variations are reworked to be based on envelopes of helicity cross sections rather than per-event weights, since these are subject to large statistical fluctuations due to the large variance in the weight distributions.
In addition, inclusive variations for each helicity cross section (except for sigma_-1) are added on top of the pt-binned variations in order to protect against underestimating the correlated part of the uncertainty.
There are also several fixes/improvements to the NP uncertainties:
-Delta_Lambda2 was missing (trivial bug)
-Lambda2/Delta_Lambda2 parameters (and Omega) are now decorrelated in gen charge, even for the non-binned case
-Lambda4 is now treated as a fully correlated parameter since we assume that any x and flavour dependence in this model is …

Rework MiNNLO scale variations and Refine NP Uncertainties

---

scripts/histmakers/w_z_gen_dists.py
wremnants/syst_tools.py

This PR restores the possibility to run the gen distributions with the propagateToHelicityOption.
It should by construction pass the CI because it doesn't affect any code which isn't under that option. After we verify that I can merge it

fixing bug in propagateToHelicityOption

---

.github/workflows/main.yml
scripts/combine/setupCombine.py
utilities/styles/styles.py
wremnants/combine_theory_helper.py

Testing if it works. For the histogram it reuses the same file as for the traditional analysis, which is augmented with the yieldsTheoryAgnostic histogram. Then the setupCombine and fit parts are simply duplicated from the standard wmass workflow.
No change should be expected for the traditional analysis in the impacts and other plots. A new plot is added for the impact from the theory agnostic fit (but it is possible the fit doesn't even converge when using a small fraction of the MC stat, to be seen).

Add theory agnostic analysis with POI as NOI to CI

---

scripts/combine/setupCombine.py
scripts/histmakers/w_z_gen_dists.py
scripts/plotting/makePdfUncPlot.py
utilities/boostHistHelpers.py
wremnants/syst_tools.py
wremnants/theory_tools.py

The bands can be produced using the script makePdfUncPlot.py and then are used by default by setupCombine to build the shapes. It's possible to increase the size of the band using the new option theoryAgnosticBandSize which defaults to 1. The size of the OOA is hardcoded to 1 and the variations on sigmaUL are always 50%, even if the band is increased. I also corrected a problem in the implementation that prevented the fit to run correctly when --hdf5 option is used. Everything has been tested locally and it works and the output makes sense. We wish to merge this ASAP (at most tomorrow morning) to run the bias tests with @jeyserma together with the traditional analysis, therefore @cippy and @davidwalter2 please tell me what you think.

Implementation of theory-motivated agnostic bands

---

wremnants/combine_theory_helper.py
wremnants/theory_corrections.py

Fixes two critical issues with the MiNNLO QCD scale variations
1) Events in gen overflow bins were receiving NaN weights.  These events now receive no QCD scale variation. 
This was especially a problem for the Z where the gen mass range is 60-120GeV (and this is already flagged as something we need to improve by adding more gen bins on the left and right so that the number of events in gen underflow/overflow surviving the reco selection becomes smaller)
In the W case this was still leading to NaN in one or a few bins (probably from events where the W is in the gen rapidity overflow)
2) The nominal was not being included in the QCD scale variation histogram, breaking the logic of the hist_to_variations function (effectively adding a spurious term proportional to the sigmaUL down …

Fix MiNNLO scale variations

---

wremnants/CardTool.py

For the root based writer of CardTool, the hdf5 one already has something now.
The check is also looking at overflow bins when present, it should be ok.
I was not sure whether to make this function a member function of CardTool, or define it elsewhere completely. Let me know

add check for Nan or inf bins in syst histograms

---

scripts/histmakers/w_z_gen_dists.py
utilities/common.py
utilities/io_tools/output_tools.py
wremnants/theory_tools.py

This PR primarily adds the boson qt bY Q variable. An option is included to select the axis ptqVgen. Subsequently, if-else conditions are implemented to store kinematics and calculate Ai with respect to this variable. Otherwise, it will proceed with ptVgen as is. Additionally, the NNPDF30 branch name has been fixed. I trust this modification will not impact or interfere with any other aspects of the code.

Add qt/Q Variable in Gen Histmaker, will not change anything else

---

scripts/ci/run_with_singularity.sh

Updated singularity image eliminates most spurious threads from Tensorflow Lite by adding a dedicated patch (previously one spurious thread per RDF-thread per tflite helper, now reduced to one thread in total for tflite)
Updated env variables in narf eliminate an addition ncores threads from Eigen.
Updated singularity image contains a general update of package versions, but also ROOT 6.30.02 (plus our patches for improved PyROOT debugging which aren't upstream yet)
narf has been adapted to implement a variation on the Progress Bar feature (but in a way which is compatible with RunGraphs)
Zero physics changes expected (but maybe some numerical differences/reshuffling depending)

Threads and progress

---

utilities/common.py
wremnants/combine_theory_helper.py
wremnants/syst_tools.py
wremnants/theory_tools.py

Added the extra herapdf20 uncertainties: https://lhapdfsets.web.cern.ch/current/HERAPDF20_NLO_VAR/HERAPDF20_NLO_VAR.info
These uncertainties are symmetrized by symmetrizing the weights around the central value and concatenated to the main herapdf20 uncertainty tensor. Symmetrization is cross-checked as well as the propagation to the fit.
This PR doesn't change the main analysis as the herapdf20 is not used.

Add extra herapdf20 uncertainties

---

scripts/recoil/makePlots.py
wremnants/recoil_tools.py

Added protection for nan MET values (pt/phi)
Removed the creation of TFlite helpers when no recoil uncertainties are applied
This PR does not change anything in the analysis

MET nan protection

---

scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
utilities/common.py
wremnants/datasets/datasetDict_v9.py
wremnants/datasets/dataset_tools.py
wremnants/muon_selections.py

There is also an option to use the old central NanoAOD, --noCustomBkgNano.
This PR also builds the path to the background samples accordingly, since the old and new NanoAOD files are kept in separate places. People should copy all the new samples, which are currently on eos here [0] at the same level of the signal samples (old background NanoAODs are in the subfolder BKGV9 instead).
**NOTE**: The extension of low mass DY sample is still being copied on eos from Pisa tier 2 (should be ready in order of tens of minutes). In order to start validating this PR as soon as possible, I am temporarily excluding that part of the sample from the list of input paths. 
It has to be added back when the copy is over before merging this PR
[0] /eos/cms/store/cmst3/group/wmass/w-mass-13TeV/NanoAOD/

Custom nano also for backgrounds

---

wremnants/HDF5Writer.py
wremnants/combine_theory_helper.py
wremnants/theory_tools.py

As in the title:
- Fix asymmetric writing in HDF5Writer (bug recently introduced in PR#357)
- Corrected the branch for AlphaS down variation for CT18
- Default average symmetrizing for PDFs
No impact on Asimov is expected, but this should fix asymmetric uncertainties in the bias tests.

Fix asymmetric HDF5 writing and AlphaS for CT18

---

scripts/histmakers/mw_with_mu_eta_pt.py

The previous definition was doing a binary comparison with 5<<1 i.e. "1010", meaning "isDecayedLeptonHadron" or "isPromptTauDecayProduct" instead of 1<<5 i.e. 100000 "isDirectPromptTauDecayProduct"

Fix bug in postfsr definition for mw histamaker

---

scripts/combine/setupCombine.py
wremnants/CardTool.py
wremnants/HDF5Writer.py
wremnants/combine_theory_helper.py

Additional "linear" and "quadratic" symmetrization modes are added.
These work by splitting a single asymmetric variation into two symmetric variations in a way which preserves the covariance matrix of the event yields.
An assumption has to be made on the intended functional form for the dependence of the event yield on the nuisance parameter for the asymmetric variation.
"linear" assumes that ln(alternate/nominal) is a piecewise linear function with a discontinuity at theta=0, while "quadratic" assumes that it is a parabola passing through 0 at theta=0 and ln(up/nominal) and ln(down/nominal) at theta=+-1
"quadratic" leads to somewhat larger uncertainties for asymmetric variations since values of theta beyond +-1 imply a larger variation of event yields.
If the underlying variation is …

Add additional symmetrization options and use 'quadratic' mode for PDFs, QCD scales and theory agnostic variations

---

scripts/corrections/make_ptv_corr.py
scripts/corrections/make_theory_corr.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/plotting/makeDataMCStackPlot.py
scripts/plotting/postfitPlots.py
utilities/boostHistHelpers.py
utilities/io_tools/input_tools.py
utilities/io_tools/output_tools.py
wremnants/plot_tools.py
wremnants/syst_tools.py
wremnants/theory_corrections.py

* New corrector that can roughly be seen as reweighing the ptV to the data (more accurate would be to use the unfolded results). This is useful for studies of the bias from the ptV modeling
* Small plotting improvements (eoscp for postfix, ignore unc. in ratio if they don't exist in hist, TNPs added to syst map)
* Function to calculate sqrt(SS) of variations (useful for plotting)

Add correction that takes ptll MC/data ratio and applies this as ptVgen corr

---

scripts/histmakers/mw_lowPU.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_lowPU.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
scripts/histmakers/w_z_gen_dists.py
scripts/histmakers/w_z_muonresponse.py
scripts/utilities/run_histmakers.sh
utilities/common.py
utilities/io_tools/input_tools.py
utilities/io_tools/output_tools.py
wremnants/datasets/datagroups.py
wremnants/helicity_utils.py
wremnants/theory_corrections.py

The main reason of this PR is to avoid memory issues (mainly in the unfolding) but it might be useful for other cases. 
- The result from the histmaker is now written not as a single dictionary but as separate dictionaries for each dataset and the meta data. This allows to process and store each dataset separately. Accordingly, the interface in utilities/io_tools is adapted, there might be cases in e.g. notebooks and "private" scripts that need to be adapted as well.
- The histmaker can now be run with "--appendOutputFile X" to append the output of the histmaker to the existing output file X. This allows to run the histmaker multiple times on different datasets (an example is added in scripts/utilities/run_histmakers.sh)

Add support for appending histmaker analysis output to existing file

---

scripts/histmakers/mw_with_mu_eta_pt.py
wremnants/theory_tools.py

Just a small fix, the code was trying to produce the theory helpers also if no appropriate process is selected to run on, but this was leading to a crash. 
This fix allows one to run a command like the following 
python scripts/histmakers/mw_with_mu_eta_pt.py  --filterProcs QCD
The change is currently added only to the W histmaker since the use case was to run only on the QCD MC (in principle one may want to run on Top or Diboson but excluding both W and Z to run faster) to get histograms much faster. It may be propagated also to the other histmakers but for them I don't think the fix is needed.

allow histmaker to run only of processes without theory corrections

---

wremnants/muon_selections.py

The default keeps the current behaviour, but at least one can reuse the same functions elsewhere (the annoying part was that defines and filters are mixed, so this change allows one to modify the condition for nMuon counts at will).
It might not be fully consistent with other parts of the code if one reuses the same histmakers, but I am actually trying to use a new one.

make nMuon selection more flexible

---

scripts/histmakers/mw_with_mu_eta_pt.py
utilities/common.py
wremnants/theory_corrections.py

This PR does two independent things:
1) it complements previously merged PR #380, which was not dealing with cases where one runs on at least one process with theory corrections (which activates their usage in the W histomaker) but at the same time there are generators for which no valid process is selected.
A new option is defined to bypass the error message and avoid that the code throws the error. 
One could also use --theoryCorr to remove the offending generators, but it is often less convenient that just bypassing the safety check.
2) In addition, it updates the way the number of cores is selected with option -j. The default is now 0, which makes ROOT use all the available cores, but at the same time one can select a single thread passing 1 (while in the previous case the selection …

Fix for missing processes with theory corrections, and fix for threads

---

wremnants/theory_tools.py

Small fixes for the PDFs and AlphaS ranges (no changes in central value for current msht20 PDF)
In particular:
1. nnpdf31: AS range should be 0.116-0.120 instead of 0.117-0.119
2. nnpdf40: AS range should be 0.117-0.190 instead of 0.116-0.120
3. pdf4lhc21: AS range should be 0.117-0.190 instead of 0.116-0.120
4. updated ct18z: LHEPdfWeightAltSet11[63-122], AS LHEPdfWeightAltSet11[122, 125] (0.116-0.120)
Info with references/links:
https://docs.google.com/spreadsheets/d/1koFXBgxfaYiKI4bRrW56wc3iBDETfM2bo1bxhiqbCGM/edit?usp=sharing

Update PDF and AS branches

---

scripts/combine/setupCombine.py
utilities/common.py
wremnants/syst_tools.py

- Get rid of arguments to run width unc, just include it by default (W in W case and Z in Z case, not both)
- Use EW fit variation as nominal. Can be swapped out for the experimental ones, but currently not as an option (would need to modify the code)
The impact of the variations is 0.02 MeV, so totally negligible. I've still included it. If the experimental range is used instead, the impact is 1.3 MeV. You can see the variations here:

Update treatment of width uncertainty

---

scripts/analysisTools/w_mass_13TeV/makeWMCvetoEfficiency.py
scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mw_with_mu_eta_pt_VETOEFFI.py
utilities/boostHistHelpers.py
wremnants/CardTool.py
wremnants/HDF5Writer.py
wremnants/muon_selections.py
wremnants/syst_tools.py

This is a preliminary implementation, which will be discussed tomorrow at the mW working meeting. **Until then this PR should not be merged.**
The mW histomaker will produce a new histogram where the fraction of the Z backgrounds where one muon fails the veto is scaled up by 100% (equivalent to assuming that the scale factor for the failed veto is 1.0, namely no change in the central value, with a 100% uncertainty.
The definition of this fraction requires selecting at least 2 postFSR muons inside the eta acceptance. It is possible to apply a minimum gen pT selection as well, but based on some studies to be shown tomorrow I would recommend applying no gen pT cut.
In setupCombine.py this uncertainty is mirrored, and further decorrelated vs eta.
**NOTE**: the eta decorrelation is currently …

implement preliminary veto uncertainty in mW analysis

---

scripts/analysisTools/templates/index.php
scripts/combine/setupCombine.py
utilities/styles/nuisance_translate.json
wremnants/Templates/index.php
wremnants/combine_theory_helper.py
wremnants/theory_tools.py

Include the PDF inflation factors and add them by default to the fit. For our default CT18Z, the inflation factor is 1.0, so this PR will not change the result.
Also fixed the luminosity to be correlated between Z and W fits, by naming them identical to "lumi".

PDF inflation factors, fix lumi uncertainty correlation between W/Z

---

scripts/combine/setupCombine.py
scripts/corrections/make_muon_response_maps.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
utilities/common.py
wremnants/include/muon_calibration.h
wremnants/muon_calibration.py

Muon scale and resolution corrections are updated to the latest inputs from @emanca
For the resolution corrections these are now applied binned in eta and using the four-parameter acbd model in pt (as opposed to the previous version which was binned in both eta and pt and smoothed in two dimensions)
New helpers are added to accommodate this and are used by default.
The central value and uncertainty scheme implemented for the moment is:
scale:
central value for data: track refit + lbl corrections + J/psi parametrized calibration (no change in procedure, parametrized calibration updated)
central value for mc: track refit + truth-assisted lbl corrections (no change in procedure or inputs)
uncertainties:
J/psi calibration statistical uncertainty with ad-hoc scaling of 2.2x
statistical …

Update muon calibration scale and resolution corrections

---

scripts/histmakers/mw_with_mu_eta_pt.py

Set goodMuons pt range as in the template using option --pt
Because of the veto selection, it is already guaranteed that there can't be more than 1 good muons, so defining goodMuons with the same pt range as the template should have no effect on the physics, but it avoids using magic numbers to define these thresholds, and also avoids having overflow bins filled and integrated over by mistake when doing projection plots.
Note that cuts can match the template range since none of our systematic variations rely on having the events on the other side of the boundary.
I also assume that the unfolding doesn't look at the reco pt overflow bins @davidwalter2 
@jeyserma In the past you had changed this setting the thresholds to 24 and 100 GeV, but I never fully understood why it was needed, please …

Set goodMuons pt range for Wmass histmaker

---

wremnants/include/muon_calibration.h

Bugfix for resolution uncertainties due to mixup of 1/pt vs q/p
No change to central values and should have only a very small change to overall uncertainty (though the resolution uncertainty itself will change a bit)

fix parameterized resolution uncertainties

---

scripts/analysisTools/plotUtils/utility.py
scripts/analysisTools/tests/buildPseudodata.py
scripts/analysisTools/tests/checkEffStatUncertaintyIso.py
scripts/analysisTools/tests/makeMtEfficiency.py
scripts/analysisTools/tests/testFakesVsMt.py
scripts/analysisTools/tests/testPlots1D.py
scripts/analysisTools/tests/testQCDisoMtCorr.py
scripts/analysisTools/tests/testShapesIsoMtRegions.py
scripts/analysisTools/w_mass_13TeV/diffNuisances.py
scripts/analysisTools/w_mass_13TeV/getCorrelationLine.py
scripts/analysisTools/w_mass_13TeV/makeImpactsOnMW.py
scripts/analysisTools/w_mass_13TeV/makeQCDMCstudy.py
scripts/analysisTools/w_mass_13TeV/makeRatioTH2.py
scripts/analysisTools/w_mass_13TeV/makeSystRatios.py
scripts/analysisTools/w_mass_13TeV/makeVertexPileupWeights.py
scripts/analysisTools/w_mass_13TeV/makeVertexStudy.py
scripts/analysisTools/w_mass_13TeV/makeWMCefficiency3D.py
scripts/analysisTools/w_mass_13TeV/makeWMCvetoEfficiency.py
scripts/analysisTools/w_mass_13TeV/mergeFilesSF2D.py
scripts/analysisTools/w_mass_13TeV/plotPrefitTemplatesWRemnants.py
scripts/analysisTools/w_mass_13TeV/plotSF.py
scripts/analysisTools/w_mass_13TeV/postFitHistograms.py
scripts/analysisTools/w_mass_13TeV/run2Dsmoothing.py
scripts/analysisTools/w_mass_13TeV/smoothLeptonScaleFactors.py
scripts/analysisTools/w_mass_13TeV/subMatrix.py
utilities/io_tools/output_tools.py

This PR tries to modify all plotting scripts in scripts/analysisTools/ to avoid using the eos mount for storing plots on eos. For now it only touches the functions to create folders and copy files.
It reuses the utility functions in **[utilities/io_tools/output_tools.py](https://github.com/WMass/WRemnants/compare/main...cippy:eoscp4plots?expand=1#diff-9db85a6d3c6388cfa13bb4fd910de29a1437e0b4bff0608c80b5eb1c7f921bff)**, with some slight modifications to comply with some requirements of stuff in scripts/analysisTools/ (although I tried to maintain the original behaviour when adding new flags).
One thing I noticed: when the temporary folder "temp" is created to store files locally before copying to eos, only the final subfolder inside it is eventually deleted, but I actually think one would …

updates to use xrdcp to create plots on eos

---

scripts/analysisTools/plotUtils/utility.py
scripts/analysisTools/tests/testFakesVsMt.py
scripts/histmakers/mw_with_mu_eta_pt.py
utilities/io_tools/output_tools.py

As the title says, since so far the copy was only acting on files, thus ignoring any subfolder in the source path.
In addition, the W histmaker is modified to remove scale factors from the QCD MC by default. This is something we were already enforcing through the noScaleFactors option when running on QCD MC alone to test the fakes. The logic is that the SF should technically apply only to prompt muons, hence not to QCD MC events (this also assumes that the QCD MC is not used for a reliable prediction of this background in the data/MC plots, but mainly to test the fake rate, so that using SF or not is irrelevant).
This PR should change nothing for the analysis (as long as the QCD MC is not used directly for any fit), and the PRvalidation plots should stay exactly the same as before, let's …

fix copy to eos for subfolders

---

scripts/analysisTools/tests/testFakesVsMt.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
utilities/common.py

The cut dphi(mu, met) > pi/4 was originally motivated by the mitigation of the fake rate dependence on mT, but after moving to the vertex agnostic isolation it seems this is no longer happening, and apparently the dependence remains regardless of this cut, so this PR sets the default threshold to 0 (namely no cut on dphi any longer).
The signal component in the signal region for W events should only be mildly affected by this change, and the difference on the total yields should mainly come from the variation of the fake background (which should be around 10-20% depending on pt).
Small differences in the Wlike analysis can be expected since the cut was also used there for consistency with the Wmass space.
Instead, the dilepton and low PU workflows should not be affected at all, since the …

Remove dphi cut between muon and met by default

---

.github/workflows/main.yml
scripts/combine/pullsAndImpacts.py
scripts/combine/setupCombine.py
scripts/plotting/postfitPlots.py
utilities/styles/styles.py
wremnants/plot_tools.py
wremnants/unfolding_tools.py

- In case the mass is fit in 3 regions, e.g. BB, BE, EE, two mass differences are fit. The mass can be fit together with mass differences of the extreme regions i.e. mBB-mEE and between the middle region and the extreme regions i.e. mBB+mEE-mBE. 
- using wlike trigger strategy for the wlike and dilepton analyses
- Supporting the fit with the w/z width and also generalizing the impact plotting scipt to scale the size of variations into MeV
- Fixing a typo in the preFSR definition for the unfolding
- Some smaller updates on the plotting

Updating mass difference and supporting width fits

---

scripts/combine/setupCombine.py
utilities/common.py
wremnants/muon_calibration.py

Resolution corrections were slightly updated, leading to a small change in the closure parameters.
The default calibration uncertainties have been updated accordingly (J/psi calibration statistical uncertainty scaling reduced from 2.2 to 2.0 and the additional ad-hoc fully correlated M uncertainty removed since it can now be covered by the scaled statistical uncertainties)
The muon response maps have also been updated since these depend on the resolution corrections.

Update calibration inputs and uncertainties

---

wremnants/combine_theory_helper.py
wremnants/theory_tools.py

Since Lambda4 could in principle be x/flavour dependent, move it to the set of non-perturbative parameters which are decorrelated between W+, W-, and Z
Actual effect is expected to be small and/or negligible.

treat Lambda4 as part of the flavour-decorrelated NP parameters

---

scripts/analysisTools/plotUtils/utility.py
scripts/analysisTools/runFit_theoryAgnosticPoisAsNoi_polVar.py
scripts/analysisTools/w_mass_13TeV/diffNuisances.py
scripts/analysisTools/w_mass_13TeV/makeImpactsOnMW.py
scripts/analysisTools/w_mass_13TeV/plotPrefitTemplatesWRemnants.py
scripts/analysisTools/w_mass_13TeV/postFitHistograms.py
scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/plotting/makeDataMCStackPlot.py
scripts/plotting/postfitPlots.py
utilities/common.py
wremnants/datasets/datagroups.py
wremnants/histselections.py
wremnants/muon_selections.py

Add a couple of options in setupCombine.py to customise the fake method to use
- choose smoothing_order, default modified to 2 (was 1) because it performs better
- override hardcoded scaling factor for the normalization of the fakes in the signal region, mainly for tests (allowing to change it or set it to 1.0, namely no scaling)
Augment the W histmaker to run a fake enriched region with muons from secondary vertices (the current selection might be improved when ntuples are reproduced, some variables for the proper matching have been added in recent NanoAOD versions, and Josh recently backported these changes to our custom NanoAOD producer)
The rest is mainly a set of updates for plotting scripts for which I might be the only user at the moment. Among other things I am trying to comply …

Some customisation for the fakes, augment W histmaker to run fake enriched control region, and miscellaneous

---

wremnants/CardTool.py
wremnants/HDF5Writer.py

In case the pseudodata is taken from an external file with the same histogram name as the nominal model the histogram of the model gets overridden and then deleted. The fix is to not load the histogram if it's already there and don't delete it.

Fix pseudodata

---

scripts/combine/setupCombine.py

Scaling of J/psi calibration uncertainties is increased from 2.0 to 2.1 following the revised procedure and discussion with the ARC.
Only effect should be a (small) increase in the calibration uncertainties obviously.
Note that a further PR refining the resolution corrections and/or uncertainties is likely.

Update scaling of J/psi calibration uncertainties

---

.github/workflows/main.yml
wremnants/datasets/dataset_tools.py

NanoProdv6 contains the extra hit count information for the muons.  Keep the old versions as fallback for the moment since the new variables are not actually used/required yet.

add updated nano production version

---

scripts/plotting/postfitPlots.py

The number of degrees of freedom for the prefit chisquared was incorrectly subtracting the number of free parameters (this is correct/necessary for the postfit saturated likelihood, but not for the prefit chisquared)
Fixed now. (plus some minor plot formatting improvement)

Fix ndof for prefit chisquared in plotting script

---

scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
wremnants/include/muon_efficiencies_smooth.h
wremnants/muon_efficiencies_smooth.py
wremnants/syst_tools.py

Fixing the helper, and updating setupCombine.py to use again this systematics.
I am slightly changing the name of groups for the veto nuisances to facilitate gathering later on, and also adding a group that includes all efficiency systematics (both stat and syst together, also with veto).
I am including a few minor changes also in the histmakers for W and Z to add some utility plots (although this mainly relate to another PR which will add some scripts to make plots with them)

Fix tracking alt bkg systematics

---

.github/workflows/main.yml
scripts/combine/setupCombine.py
scripts/corrections/make_theory_corr_ew_powhegFO.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
scripts/histmakers/w_z_gen_dists.py
utilities/common.py
wremnants/combine_helpers.py
wremnants/datasets/datasetDict_gen.py
wremnants/include/csVariables.h
wremnants/syst_tools.py
wremnants/theory_tools.py

The virtual EW corrections and uncertainties. are implemented for Z from Powheg Fixed Order.
This is done differential in (prefsr) mass, absolute rapidity, and CS costheta*.
The uncertainties are currently implemented as the full (symmetrized) variation from the pole scheme as well as the alpha EM scheme (0.2 MeV for the wlike), and the full size of the correction (0.5 MeV for wlike).  Possibly something like 0.1 times the correction would be more reasonable, but this is already pretty small.
The sin2theta variation is added from MiNNLO rather than from the NLO EW sample, because otherwise the full EW correction/uncertainty would probably have to be rapidity-dependent.   The sin2theta impact on the mass uncertainty is totally negligible.
@mseidel42 @amsimone (sorry I don't know Federico's …

Add Virtual EW corrections for Z from Powheg Fixed Order and add sin2theta variation for Z

---

.github/workflows/main.yml
scripts/combine/setupCombine.py
utilities/common.py

This should be merged as soon as the checks pass since otherwise there is a fairly serious problem introduced in the wlike fit (where scetlib+dyturbo variations on the Z do not properly have the electroweak correction weight applied)

Temporarily disable virtual EW corrections for the Z since they cause inconsistencies with the QCD uncertanties

---

.github/workflows/main.yml
scripts/combine/setupCombine.py
scripts/corrections/make_theory_corr_ew_powhegFO.py
scripts/corrections/make_theory_corr_ew_renesance.py
scripts/corrections/make_theory_corr_ew_renesance_smooth.py
utilities/common.py
wremnants/combine_helpers.py
wremnants/datasets/datasetDict_gen.py
wremnants/theory_corrections.py
wremnants/theory_tools.py

The photos ME correction off uncertainties have been updated using the new MC samples that really switch off the ME corrections for the W.
The electroweak variations have been reverted to not apply to the central value since this caused some technical problems/inconsistencies (but there are also concerns about introducing inconsistencies via the breaking of the angular decomposition)
The powheg FO EW virtual uncertainties are restored for the Z, and renesance EW virtual uncertainty is added for the W , applied three-dimensionally in prefsr mass, absY and costhetastar.

Update electroweak corrections and uncertainties

---

scripts/histmakers/w_z_gen_dists.py
wremnants/combine_theory_helper.py
wremnants/include/csVariables.h
wremnants/include/theoryTools.h
wremnants/syst_tools.py
wremnants/theory_corrections.py
wremnants/theory_tools.py

This fixes a serious bug in the construction of the helicity moments histograms where all of the alternate electroweak samples were accidentally being summed together with the signal samples.
The tau samples have now also been removed from the moment calculation since although they were previously included intentionally, small differences in angular coefficients have been observed, likely due to momentum reshuffling when pythia adds the tau mass.
In addition to the above critical update of the inputs used to construct the QCD scale variations split by helicity, the binning for the weight computation is also slightly refined.  (The ptV binning for the actual uncertainties is unchanged.)
An additional uncertainty has been added for the difference in angular coefficients at preFSR vs LHE …

Updates to helicity uncertainties

---

scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
utilities/common.py
wremnants/combine_theoryAgnostic_helper.py
wremnants/combine_theory_helper.py
wremnants/helicity_utils_polvar.py

This PR adds the option to replace MiNNLO muR/muF binned variations with continuous polynomial variations as in the theory agnostic implementation by the ERC ASYMOW group. To do this you run setupCombine.py with the "--muRmuFPolVar" option. This is implemented both the W mass analysis and the W-like analysis, and it doesn't require to define an out-of-acceptance dataset.

Added option to replace MiNNLO muR/muF binned variations with continuous polynomial variations

---

wremnants/combine_theory_helper.py

Previously the inclusive scale variation was just added on top of the binned ones.  Since there are only 10 bins, this in principle results in an overestimate of the fully correlated component by ~5%, which is removed by scaling down the inclusive variation by the corresponding amount.
The appropriate inclusive variation is also added on top of the polynomial scale variations when these are used (though this may be replaced with an inclusive variation from the polynomials themselves at some point)
There were also some cases where theory uncertainties were not being added to the appropriate groups, which is improved now (but a broader harmonization of the groups with some kind of coherent naming scheme would be very good indeed)

Remove double counting between inclusive and binned QCD scale variations and add inclusive variation for polynomial case

---

scripts/combine/setupCombine.py

Small addition:
When running with lowPU, the arguments should be set with args.fakeEstimation as 'simple' and args.binnedFakeEstimation. The error given when these are not set is not useful for finding this possible oversight; this update gives a logger.error message instead. See lines 197-199 added.
Apologies for all the 'extra' edits, as I had an IDE (now-removed) setting that removes all extraneous spaces at the ends of lines!

Add error message for incorrect lowPU args

---

wremnants/combine_theory_helper.py

The scaling factor was slightly (less than 1%) wrong for the nominal case.
The scaling has also been removed for the case of the polynomial variations, since there shouldn't actually be any double counting in that case.

fix scaling of minnlo inclusive scale variations

---

scripts/combine/setupCombine.py
wremnants/combine_theory_helper.py

Allow for multiple luminosity inputs and baseNames, to correspond with multiple input files. If not specified, default values are used for all files.
updated from previous PR

Multiple luminosity inputs for multiple files in setupCombine

---

wremnants/theory_tools.py

Updated the variation in alphaS to have renorm = True. Previously, this correction on non-CT18Z default pdf sets was not multiplicative (see here, with running on nnpdf31 set/lowPU conditions):
After the edit is applied, alphaS is centered:

Applies new pdf as multiplicative correction (not absolute) for alphaS

---

scripts/histmakers/mw_with_mu_eta_pt.py
wremnants/helicity_utils.py
wremnants/include/syst_helicity_utils.h
wremnants/muon_calibration.py
wremnants/syst_tools.py
wremnants/theory_tools.py

Currently, we have a separate helper for each systematic uncertainty to add the helicity axis. In this PR I replaced most of it by generic functions to more easily add systematic in the future and maintain the cases with and without helicity axis. 
I also made a small modification in the [muon_calibration.py](https://github.com/WMass/WRemnants/compare/main...davidwalter2:240627_restructure_helicity_utils?expand=1#diff-bd883547941e3fe5de15db4ea2f5a7a72f6a7f5f012d27dd2d426b7295c0f7a7) to avoid the division by 0 warning when running the histmaker.

Restructure helicity utilities

---

scripts/histmakers/mw_with_mu_eta_pt.py
utilities/common.py

Currently, there are several bins in high mT and high Iso that would be needed for the extended 2D ABCD method, but since we are using the extended 1D as default and don't plan to switch to 2D in the near future we can reduce these bins and reduce the histogram size, and with this also resource consumption.

Reduce default bins in mt and iso for abcd method

---

utilities/common.py

As the title suggests, now the polynomial variations include the dependence on the rapidity of the bosons. The variations are fully correlated in rapidity and decorrelated in pt as before. The fully correlated component as a function of pt is still the binned one, this could be implemented in a later PR-

Added dependence of the MiNNLO polynomial variations on the rapidity

---

scripts/histmakers/mw_lowPU.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mw_with_mu_eta_pt_VETOEFFI.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
scripts/histmakers/w_z_gen_dists.py
scripts/histmakers/w_z_muonresponse.py
scripts/plotting/makeDataMCStackPlot.py
scripts/plotting/makePdfUncPlot.py
scripts/plotting/plot_angular_coefficients.py
scripts/plotting/response_matrix.py
wremnants/__init__.py
wremnants/helicity_utils.py
wremnants/include/syst_helicity_utils.h
wremnants/plot_tools.py
wremnants/qcdScaleByHelicity_helper.py
wremnants/recoil_tools.py
wremnants/syst_tools.py
wremnants/theoryAgnostic_tools.py
wremnants/theory_corrections.py
wremnants/theory_tools.py
wremnants/unfolding_tools.py
wremnants/vertex.py

- Rename a few places where helicity cross sections were incorrectly denoted as angular coefficients or moments, and vice versa. 
- Remove relative imports to improve code readability
- The files in wremnants-data/data/angularCoefficients are still incorrectly denoted as "moments" but contain helicity cross sections, this will be changed in a future update.

Adapt/clarify helicity utilities 

---

scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/utilities/split_hists.py
utilities/common.py
utilities/io_tools/output_tools.py
wremnants/include/utils.h

Add new functionality for bootstrapping of MC and data to produce toys in the histmaker.
A new option is also added to automate the running of the event loops in series to save memory (useful when running many toys in parallel)
Some performance optimizations have been made to the boot histogram conversion in narf, which is relevant since the histograms can become very large with many toys.
Some combinetf2 updates as well to support the statistical studies (initial implementation of binByBin uncertainties and toys)
There is also a bug fix in setupCombine which was not correctly propagating systematic uncertainties to the fakes in case groups were being filtered.
This should have no effect on standard workflows.

Implement bootstrapping of MC and data for toys

---

.github/workflows/main.yml
scripts/analysisTools/runFit_theoryAgnosticPoisAsNoi_polVar.py
scripts/combine/setupCombine.py
scripts/plotting/makeDataMCStackPlot.py
scripts/recoil/functions.py
utilities/boostHistHelpers.py
wremnants/combine_helpers.py
wremnants/datasets/datagroups.py
wremnants/histselections.py

This implements smoothing of the full fake estimate with exp(pol2) by default.  This doesn't work in the presence of additional axes currently, so it's disabled e.g. when plotting other variables like mT etc (and we'll need to find a more general solution for this for the mT fit if we want to use it)
The rebinning used in the pt axis is the same as for the current fakerate smoothing.
The polynomial type and rebinning are now steered automatically as part of the --fakeSmoothingMode option by default. (bernstein with non-negative least squares for fakerate smoothing, and power basis with standard least squares for fake estimate smoothing since that is done in the log space)
There is also a technical change to the handling of the EW ISR and FSR uncertainties to move the selection of …

Implement smoothing of full fake estimate and enable by default

---

scripts/combine/saturatedGOF.py
scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/plotting/fakerate.py
scripts/plotting/makeDataMCStackPlot.py
scripts/plotting/postfitPlots.py
utilities/boostHistHelpers.py
wremnants/CardTool.py
wremnants/HDF5Writer.py
wremnants/datasets/datagroups.py
wremnants/histselections.py
wremnants/muon_selections.py
wremnants/plot_tools.py

- Adapt the implementation of the full smoothing to make it work for simple and extended2D. This was mainly done by moving the functions into the ```FakeSelectorSimpleABCD``` class, that gets inherited by the extended methods. 
- Add nonclosure corrections in histselector class to be used with QCD MC histogram (off by default). In the future we could change to this to automatically scale the fakes and avoid hard coded scale factors (or even make a pT-eta dependent correction, to be decided)
- Reverting the muon selection for the secondary vertex control regions, as the new selection by index does not look as expected (seeing way more prompt contamination)
- Adding a protection in the hdf5 writer for bins with sumw2=0 (setting ```kstat = np.where(np.equal(sumw2,0.), 1., kstat)```)
- A few …

Updates on fakes

---

scripts/combine/setupCombine.py
wremnants/CardTool.py
wremnants/HDF5Writer.py

Default for mW fit is set to 1.125 following the bootstrap studies.

add scaling of mc statistical uncertainty

---

scripts/plotting/postfitPlots.py

Fix bin width normalization which was inconsistent in some cases, and add option to skip printing the chisquared values on the plots (since sometimes it doesn't make sense, e.g. when the same or overlapping data is used for the external postfit result)

Minor updates to postfit plotting script

---

.github/workflows/main.yml
.github/workflows/unfolding.yml
scripts/combine/setupCombine.py
wremnants/CardTool.py
wremnants/HDF5Writer.py

Make hdf5 output the default and deprecate ROOT output (can still force it if needed)
Also makes the exponential transformation of yields used for the gen level fit to helicity cross sections an explicit option rather than hardcoding it based on the nominal histogram name.
No changes expected in the ci except for maybe numerical differences for some of the workflows which are switch from ROOT output to hdf5. (but we should make sure any differences are carefully understood)

hdf5 output by default and make exponential transform an explicit option

---

scripts/combine/saturatedGOF.py
scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/plotting/fakerate.py
scripts/plotting/makeDataMCStackPlot.py
utilities/common.py
wremnants/datasets/datagroups.py
wremnants/histselections.py

This is a continuation of #502 
- Implement full smoothing by smoothing each sideband region independently and implicitly evaluate signal region 
- Monotonic smoothing based on integrated Bernstein polynomials is used to have a stable smoothing
- Smoothing order is set to 3
- Fake normalization is scaled by 0.85 and the uncertainty is set to 5% (for extended 1D, which is still the default)

Update of fakes

---

.github/workflows/main.yml

This was mistakenly switched to use the asimov dataset when hdf5 output was made the default in https://github.com/WMass/WRemnants/pull/512

restore use of real data for dilepton ptll-yll fit

---

scripts/combine/setupCombine.py

This is needed to have fully consistent treatment of the mZ NOI when doing postfit plots of dilepton kinematics using external postfit results from the W-like for example.

make forcing of mass constaints on or off more flexible

---

scripts/combine/setupCombine.py
wremnants/CardTool.py

This PR partially reverts https://github.com/WMass/WRemnants/pull/492/files and fixes a bug that was in the previous version of the code.
Usually the code would skip any nuisance that ends up being applied to no process in the list of requested ones. Typically this can happen when excluding processes for tests (e.g. when running with signal only). For lnN syst the logic was bugged because the function deals with the whole set of defined LnN syst, and it was returning as soon as one lone nuisance applied to no process was appearing, while it should just continue and move to the next lnN.
For shape systs the logic is the same but in that case returning is fine, because the corresponding function deals with all nuisance handled by a single call to CardTool.addSystematics (e.g. all effStat, …

Skip nuisance parameters that would affect no processes when preparing the fit setup 

---

scripts/combine/pullsAndImpacts.py
scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/plotting/postfitPlots.py
utilities/common.py
utilities/styles/nuisance_translate.json
utilities/styles/styles.py
wremnants/CardTool.py
wremnants/histselections.py

- For monotonic polynomials (integrated bernstein polynomials) allow integration constant to flip sign by repeating non-negative least squares. For the signal region the distribution could still be non monotonic, thus, the non-negative least squares is evaluated on the linearly combined parameters and covariance matrices to impose monotonicity, again, with excluding the integration constant. 
- Set variance to inf for log if events are 0, this results in a weight of 0
- adding uncertainties from QCD MC nonclosure

Update on fakes

---

scripts/analysisTools/w_mass_13TeV/validateIsoMtRegionsWithZ.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py

This is used for the validation of muon SF with Wlike events, using the same isolation and mt bins relevant for the mW analysis.
Nothing should change for the standard workflows, but it is useful to have these features implemented in the main code for future iterations. Given the histograms, one can them even fit single bins selected in setupCombine using the already existing options --fitvar and --axlim options, adding isolation and mT in the list of fit axes and using specific bins.

Update Wlike histmaker allowing iso-mt axes to be added to the list of nominal axes

---

scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py

Simple updates to run some tests, which might be needed also in the future.
One option allows the user to remove veto SF (whatever their definition is), while the other two permits the scaling of the DY backgrounds by a constant, either the full background or only the fraction that would be affected by the veto SF (these two options can be used in conjunction with the one that removes the veto SF).
For consistency, when removing veto SF the corresponding uncertainties are also not created.
No change is expected for the main workflows

Utility options for W histmaker to test veto SF 

---

scripts/combine/setupCombine.py
scripts/plotting/controlPlotsHDF5.py
scripts/plotting/makeDataMCStackPlot.py
scripts/plotting/postfitPlots.py
utilities/common.py
wremnants/CardTool.py
wremnants/HDF5Writer.py
wremnants/datasets/datagroups.py
wremnants/histselections.py
wremnants/regression.py

- Refactoring of QCD background smoothing machinery: Adding new "Regressor" class to take care of the smoothing and contains related information such as parameters and covariance matrix. This allows to have multiple Regressor objects in case multiple smoothing are performed.
- Implement "hybrid" smoothing mode to smooth the fakerate and the application region independently
- Update uncertainties on QCD background: Previously the nonclosure from QCD MC was taken as uncertainty together with its statistical uncertainty. This led to statistical problems that were previously solved by the smoothing. The additional uncertainties are now removed and instead a single fully correlated variation of the O(x) smoothing parameter is added. It is validated in bias tests that this uncertainty covers …

Update QCD background: smoothing, uncertainties, and bias tests

---

scripts/combine/setupCombine.py
scripts/histmakers/mz_dilepton.py

This is needed to facilitate different combinations of W+Z simultaneous fits for some of the cross checks.
There is also what is technically a fix here to the default/automatic behaviour for the yll-ptll (or yll-ptll+W combined fit) where previously although mZ was correctly constrained, it was constrained with a 100MeV uncertainty instead of the 2.1MeV PDG uncertainty.  Of course when fitting non-mass-sensitive observables this should make very little difference.
This PR should have zero change to the nominal fit or the CI.

Make massDiff and mass constraint behaviour more configurable

---

wremnants/combine_theory_helper.py

Previously not included because of misunderstanding, it's part of the official W mass unblinding of the HCSF.

adding shower kt uncertainty to HCSF

---

wremnants/combine_theory_helper.py

Add "Lambda_Correlated" and "Delta_Lambda_Correlated" non-perturbative models which fully correlate the non-perturbative uncertainties between W+, W- and Z
This is intended to test alternate versions of the fit with stronger (and possibly incorrect) theoretical assumptions.
No change expected in the CI since these models are not used by default.

Add additional non-perturbative models

---

scripts/ci/run_with_singularity.sh
wremnants/include/EtaPtCorrelatedEfficiency.h

Singularity is updated to v38 with cppyy error handling patches restored for new ROOT version (and addition of various python linter packages)
Some associated technical changes are also included, removing unneeded workarounds and a some fixes for deprecated or non-standard C++ features which will eventually cause warnings in future ROOT/llvm/clang versions.

Update ROOT with cppyy error handling patches + associated technical changes

---

.github/workflows/cleanup.yml

When the old kerberos ticket expires a /tmp/krb5cc_158524 remains and has to be manually deleted to create a new one. 
Added the deletion in the cleanup workflow now that is run once a week.

Automatic deletion of old kerberos credentials

---

scripts/combine/setupCombine.py
scripts/histmakers/w_z_gen_dists.py
wremnants/include/utils.hpp
wremnants/syst_tools.py
wremnants/theory_tools.py

This is done by adding the helicity weights as an extra column so that it is ~automatically added to all histograms.
Since multiple tensor weights are not supported yet, the helicity weights are added as an array together with an array of indices, so this could be made more computationally efficient in the future.
Example usage
`python $WREM_BASE/scripts/histmakers/w_z_gen_dists.py --theoryCorrections --maxFiles 100 --helicity --addHelicityAxis -p helicityqcd`
`python $WREM_BASE/scripts/combine/setupCombine.py -i w_z_gen_dists_scetlib_dyturboCorr_maxFiles_100_helicityqcd.hdf5 --fitvar ptVgen-absYVgen-helicitygen -n nominal_gen --filter Wmunu
`

Optionally add helicity axis to gen histograms

---

scripts/analysisTools/tests/testPlots1D.py
scripts/analysisTools/w_mass_13TeV/makeImpactsOnMW.py
scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
wremnants/HDF5Writer.py
wremnants/datasets/datagroups.py

The option to scale histogram variance linearly to make projections to different luminosities was not correctly propagated to the HDF5 writer from CardTool. This PR fixes that.
This PR also removes the obsolete option --halfStat from the W histmaker, which was running with half stat by directly cutting on the event parity. This option didn't really work as it was originally intended, because the data histogram is effectively cut in half, but the target luminosity doesn't change because it is computed before selections, so the MC is eventually scaled to the original data set resulting in twice the yields than in data.
There are few minor fixes in other plotting scripts.
No change is expected from CI

Fix lumi scaling

---

scripts/combine/setupCombine.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
wremnants/muon_prefiring.py
wremnants/syst_tools.py

Muon prefiring for 2017 and 2018 is expected to be very small.
So far we were propagating the same uncertainties as in 2016 postVFP, but this is too conservative.
This PR changes it to use the uncertainties stored in the NanoAOD, which for these cases should be sufficient (can be decorrelated in setupCombine if needed, but for now it is not done).
The functions in syst_tools to define the prefire uncertainties are updated to include this change, and also made more modular.
No change is expected for the main analysis or the low PU (the latter already uses its own code for the prefiring)

use proper prefiring uncertainties for years which are not 2016postVFP

---

.github/workflows/main.yml
.github/workflows/unfolding.yml
scripts/ci/run_with_singularity.sh
wremnants/plot_tools.py

includes updated versions of most dependencies
A small formatting change was needed due to a change in black apparently
Since black support for jupyter notebooks has been added to the container, the notebooks are explicitly excluded from the linting for the moment.
tensorflow_io has also been removed from the singularity and its dependency removed from combinetf2 since this was blocking the update to tensorflow 2.18 and does not appear to be well maintained recently.

Update container to v42

---

scripts/combine/setupCombine.py
wremnants/datasets/datagroups.py
wremnants/histselections.py

This PR allows the ABCD method to run whatever thresholds are used for the ABCD axes in the input histograms. The previous code was hardcoding those values internally in histselections.py
The nominal analysis does not change, since the hardcoded edges were tuned for that.
This PR also adds a new option --ABCDedgesByAxis to setupCombine.py to explicitly set the edges to be used for any axis in the ABCD method (for example, --ABCDedgesByAxis "mt=0,20,40", where the signal region is just everything above 40). This is useful when the necessary axis contains more edges than needed for the ABCD method itself and it is not possible to automatically choose those that should be used for the ABCD method (usually they are evaluated based on a set of default values, to ensure the axis can be rebinned …

set ABCD thresholds based on histogram axis's edges

---

scripts/histmakers/mw_lowPU.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_lowPU.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
scripts/histmakers/w_z_gen_dists.py
scripts/rabbit/feedRabbitTheory.py
scripts/rabbit/setupRabbit.py
utilities/common.py
wremnants/combine_theory_helper.py
wremnants/include/theory_corrections.hpp
wremnants/include/utils.hpp
wremnants/syst_tools.py
wremnants/theory_corrections.py
wremnants/theory_tools.py
wremnants/unfolding_tools.py

- implemented PDF, quark mass, alphaS systematics the same way we currently do the QCD scales: through the helicity cross sections in the Z and W and gen histmakers. PDF and alphaS variations by helicity are produced via the gen histmaker, with the same binning for W and Z.
- implemented option to use these boson-parametrized systematics in setupRabbit.py, which are now default. An option has been added to use the 'old' systematics from the MINNLO weights
- implemented W in the theory fit, can now fit Z & W together

Theory systematics through helicity cross sections; W theory fit

---

scripts/histmakers/mw_lowPU.py
scripts/histmakers/mw_with_mu_eta_pt.py
scripts/histmakers/mz_dilepton.py
scripts/histmakers/mz_lowPU.py
scripts/histmakers/mz_wlike_with_mu_eta_pt.py
scripts/histmakers/w_z_gen_dists.py
wremnants/include/histHelpers.hpp
wremnants/include/theory_corrections.hpp
wremnants/syst_tools.py
wremnants/theory_corrections.py
wremnants/theory_tools.py

- The central PDF weights are parametrized via the boson helicity cross sections. This is a similar procedure as is already applied to the PDF, alphaS, QCD scale variations
- Fix from previous PR: the PDF variations times the nominal weight were being clipped, now clipping PDF variations only. Although, this doesn't really matter now that we don't use event weights to get the variations.

Parametrize central PDF weights via the boson helicities
